//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceReminder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime SubmitedDate { get; set; }
        public string FileHash { get; set; }
        public byte TypeId { get; set; }
        public Nullable<short> ReminderId { get; set; }
    
        public virtual Reminder Reminder { get; set; }
    }
}
