//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceReminder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice : Document
    {
        public Nullable<float> NetAmount { get; set; }
        public Nullable<byte> TaxRate { get; set; }
    }
}
